title: Drop Menu
variants:
  - name: default
    context:
      text: Help
      url: /test/url
      type: div
      items:
        - url: /test/url1
          text: Link 1
        - url: /test/url2
          text: Link 2
        - url: /test/url3
          text: Link 3
        - url: /test/url4
          text: Link 4
  - name: account
    context:
      url: /account/
      type: div
      class: 'drop-menu--align-right'
